name: compolvo-backend
services:
  mariadb:
    container_name: mariadb
    image: mariadb:11.3
    ports:
      - target: 3306
        published: 3306
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: compolvo
  compolvo-server:
    container_name: compolvo-server
    depends_on:
      - mariadb
    ports:
      - target: 8000
        published: 8000
    environment:
      DB_HOSTNAME: mariadb
    build:
      context: .
      labels:
        - compolvo-server:latest