POST http://localhost:8000/auth

{
  "email": "test@example.com",
  "password": "test"
}

###

GET http://localhost:8000/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjpudWxsLCJleHAiOjE3MTI4NTU0MzV9.xvuZ4hrwyAaT0cJOMOMt2nBKGBTnBtNHI8xA9-A0RiA