POST http://localhost:8000/api/service/offering

{
  "name": "month",
  "price": 1290.99,
  "duration_days": 30,
  "service": "0bf5f457-df08-4025-ac14-c79707648807"
}

###

PATCH http://localhost:8000/api/service/offering?id=e803c9fb-926f-4ca8-b256-e49b39048cba

{
  "name": "year"
}

###

DELETE http://localhost:8000/api/service/offering?id=b1046e1a-63ab-44b0-bcbc-0a8b63fde201