POST http://localhost:8000/api/service/offering

{
  "name": "monthly",
  "price": 29.99,
  "duration_days": 30,
  "service": "a576d76d-3f62-41f0-b8fa-22713372ec2b"
}

###

PATCH http://localhost:8000/api/service/offering?id=b1046e1a-63ab-44b0-bcbc-0a8b63fde201

{
  "name": "Docker Desktop (monthly)",
  "price": 24.99
}

###

DELETE http://localhost:8000/api/service/offering?id=b1046e1a-63ab-44b0-bcbc-0a8b63fde201