POST http://localhost:8000/api/service

{
  "name": "compolvo-server",
  "description": "Demo description",
  "license": "MIT",
  "download_count": 69,
  "retrieval_method": 1,
  "retrieval_data": {
    "link": "http://localhost:8000/api/version",
    "regex": "(?<version>.+)"
  }
}

###

PATCH http://localhost:8000/api/service?id=52df2bad-8e34-4472-8920-19b79312d423

{
  "name": "Compolvo (Server)",
  "retrieval_method": 2
}

###

DELETE http://localhost:8000/api/service?id=52df2bad-8e34-4472-8920-19b79312d423