services:
  - system_name: nginx
    template: apt_homebrew_choco_pacman.yml.jinja
    versions:
      - 1.25.5
      - 1.25.4
      - 1.25.3
      - 1.22.1-9
  - system_name: git
    template: apt_homebrew_choco_pacman.yml.jinja
    versions:
      - 1:2.39.2-1.1 # Debian
      - 2.45.0 # Homebrew