/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Compact_card: typeof import('./components/compact_card.vue')['default']
    CreateAgentDialog: typeof import('./components/CreateAgentDialog.vue')['default']
    Detailed_card: typeof import('./components/detailed_card.vue')['default']
    Filter_panel: typeof import('./components/filter_panel.vue')['default']
    First: typeof import('./components/first.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginForm: typeof import('./components/LoginForm.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    RegisterForm: typeof import('./components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
